baseURL = 'https://example.org/'
theme   = 'Mingger'
title   = 'Mingger'
defaultContentLanguage = 'zh'

[params]
  blogName    = "Mingger"
  description = "一个简单的个人博客。"
  favicon     = "/static/favicon.ico"
  homeExtra   = "这里可以写一些额外的文字，比如座右铭或最新动态。"

[outputs]
  home    = ["HTML"]
  section = ["HTML", "RSS"]
  page    = ["HTML"]

[markup.goldmark.renderer]
  unsafe = true
